name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build . --file ./Dockerfile --tag ghcr.io/eoluchile/edx_photo_verification:${GITHUB_SHA}

      - name: Test image
        run: docker run --rm ghcr.io/eoluchile/edx_photo_verification:${GITHUB_SHA} python manage.py test

      - name: Push
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u eolito --password-stdin
          docker ghcr.io/push eoluchile/edx_photo_verification:${GITHUB_SHA}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
